var introducao = '<img src="imgs/introducao.png" alt="" ><section><p>A história se passa em um mundo dotado tecnologicamente, onde a cada dia que passa, os avanços tecnológicos ganham forças. Um jovem estudioso e programador, começa a se aprofundar nos seus estudos. Após estudar muito, percebe que o mundo em que ele vive, existe algo de errado. A humanidade foi controlada pelas máquinas que criaram uma realidade virtual, pessoas dentro da realidade, desconfiaram que o mundo em que elas viviam, existia algo de errado.</p><div class="botoes"><a  href="#" onclick="carregarConteudo(inicio);" class="btn">Iniciar</a></div></section>';

var inicio = '<img src="imgs/inicio.jpg" alt="" height="500px"><section><p>Numa noite excepcionalmente iluminada pelas várias luzes da cidade, após muitos estudos e horas no computador, o jovem saiu de um quarto velho e empoeirado, olhando para sua janela e observando a paisagem com grandes prédios que lhe cercam, pensou em aproveitar a vida de um modo diferente, visto que aproveitar no seu ponto de vista, era passar horas de frente do computador. Pensou nos seguintes lugares: Boteco velho do seu bairro e Bar de um bairro nobre.</p><div class="botoes"><a  href="#" onclick="carregarConteudo(botecoVelho)" class="btn">Boteco velho</a><a onclick="carregarConteudo(barNobre)" class="btn">Bar do bairro nobre</a></div></section>';

var botecoVelho = '<img src="imgs/botecoVelho.jpg" alt="" height="500px"><section><p>O jovem programador, não se sentiu muito bem ao entrar no boteco velho, não estava acostumado com aglomerações de pessoas e, como dissemos anteriormente, ele passava horas de frente do seu computador, sempre evitando companhias. Dessa vez, parecia se sentir diferente, sentia o desejo de estar com outras pessoas. A primeira pessoa que teve contato no boteco, foi um velho bêbado que buscava esquecer a tristeza de sua separação na bebida. O jovem se identificou com toda essa melancolia, resolvendo desabafar por meio de suas ideias e pensamentos mirabolantes. Mas o velho não entendeu nada, achava que o jovem estava mais louco que ele próprio que estava bêbado.</p><div class="botoes"><a onclick="carregarConteudo(darRisada)" class="btn">Continuar conversa</a><a onclick="carregarConteudo(irEmbora)" class="btn">Ir embora</a></div></section>';

var barNobre = '<img src="imgs/barNobre.jpg" alt="" height="500px"><section><p>O jovem não estava acostumado com lugares chiques, nunca tinha saído de sua zona habitual, mas ficou empolgado ao ver uma moça bonita, com sua vistosa e lustrosa jaqueta. Apesar de sua insegurança e, sua incapacidade de conversar com estranhos, ele resolveu tomar atitude, convidou essa jovem moça para a sua mesa. Mesmo estando desempregado e com o nome sujo, o jovem programador, pediu para o garçom o whisky mais caro, para impressionar a garota que acabava de conhecer. Porém, essa garota não prezava por essas coisas, mas sim por um bom papo. O motivo do jovem programador sair de casa, não era arrumar uma namorada, mas sim desabafar.</p><div class="botoes"><a onclick="carregarConteudo(contarEstudo)" class="btn">Contar o que está estudando</a><a onclick="carregarConteudo(paquerarGarota)" class="btn">Paquerar garota</a><div></section>';

var contarEstudo = '<img src="imgs/contarEstudo.jpg" alt="" height="500px"><section><p>Conversando com a garota, descobriu que além de bonita, era também uma moça estudiosa. A moça, tinha os mesmos gostos musicais do jovem, torciam para o mesmo time de futebol e gostavam dos mesmos filmes. Algo que os diferenciavam, eram as suas profissões, ela era Bióloga e ele programador. Após conversarem sobre cultura pop, resolveram conversar sobre a origem da vida, isso mesmo, conversaram sobre a origem da vida num bar, perceberam que tinham as mesmas dúvidas, ambos duvidavam de suas próprias origens e o mundo que os cercavam. Era a primeira vez que o jovem conseguia ter uma conversa tão ampla como essa, como também era a primeira vez que ele conseguia conversar com uma garota por mais de 1 minuto.</p><div class="botoes"><a onclick="carregarConteudo(criarSite)" class="btn">Criar um site com ela</a><a onclick="carregarConteudo(divulgarcomPessoas)" class="btn">Divulgar para todas as pessoas</a></div></section>';

var divulgarcomPessoas = '<img src="imgs/divulgarcomPessoas.jpg" alt="" height="500px"><section><p>O jovem e a garota, resolveram divulgar seus pensamentos com pessoas do bairro, tempos depois, resolveram expandir isso para cidades vizinhas. Algumas pessoas acreditaram neles, mas a grande maioria, desacreditou. A maioria das pessoas que acreditaram neles, não entendiam absolutamente nada de tecnologia, por conta disso, o processo para que eles conseguissem fugir do mundo virtual, demorou. Mas no fim das contas, eles conseguiram. Alguns ficaram felizes por isso, mas outros ficaram tristes, pois achavam a realidade virtual muito melhor que a vida real.</p><div class="botoes"><a onclick="carregarConteudo(introducao)" class="btn">Jogar de novo</a></div></section>';

var criarSite = '<img src="imgs/criarSite.png" alt="" height="500px"><section><p>O jovem e a moça, resolveram criar sites, blogs e páginas nas redes sociais, contando sobre seus estudos. Realizaram diversas postagens, comprovando com eficácia que eles viviam em um mundo virtual e, que eles estavam sendo controlados por máquinas. Receberam muitos adeptos, pessoas que realmente confiavam naquilo. Muitas pessoas não acreditaram, mas mesmo assim, eles levaram a idéia para frente. Criaram grupos organizados de hackers, conseguiram se desconectar daquele mundo virtual. Os que acreditaram e realmente estudaram a fundo, foram felizes em suas escolhas, os que ignoraram e zombaram, viveram até o resto de suas vidas no mundo manipulador, visto que quando morriam na vida real, eram desconectados do mundo virtual.</p><div class="botoes"><a onclick="carregarConteudo(introducao)" class="btn">Jogar de novo</a></div></section>';

var casaEstudar = '<img src="imgs/casaEstudar.jpg" alt="" height="500px"><section><p>O jovem desanimado com todos acontecimentos, voltou para sua casa, continuou estudando programação, mas perdeu as esperanças na humanidade. Mesmo sabendo que o mundo em que ele vivia era uma farsa, desistiu de avisar as pessoas sobre isso, achava que ninguém iria acreditar nele. Viveu em um mundo muito inovador e tecnológico, mas se sentia angustiado. Durante sua vida, se casou, teve filhos, mas nunca encontrou a felicidade.</p><div class="botoes"><a onclick="carregarConteudo(introducao)" class="btn">Jogar de novo</a></div></section>'

var darRisada = '<img src="imgs/darRisada.jpg" alt="" height="500px"><section><p>Com conversas indo e vindo e risadas do povo que achava tão estranho esse assunto, eles gostaram do garoto e suas ideias malucas, e deram a dica de encontrar alguém tão maluco pra acreditar em algo assim, em lugares com gente que pode mudar o mundo, como lugares de rico, com isso em mente, ele se encontra com a opção de voltar e ir para o bar de ricos ou somente ir embora para casa estudar.</p><div class="botoes"><a onclick="carregarConteudo(barNobre)" class="btn">Ir ao bar de ricos</a><a onclick="carregarConteudo(irEmbora)" class="btn">Ir para casa</a></div></section>';

var paquerarGarota = '<img src="imgs/paquerarGarota.webp" alt="" height="500px"><section><p>Saindo do bar, no meio do caminho o jovem pergunta se ela gostava de jogar video-games, e ela responde que ama principalmente jogos multijogador que envolva tecnologia e biologia, pensando nisso ele rapidamente pensa em convida-la para ir uma partida. De video-game.</p><div class="botoes"><a onclick="carregarConteudo(fazerConvite)" class="btn">Fazer o convite para ela</a><a onclick="carregarConteudo(deixardeLado)" class="btn">Esquecer ideia e sair</a></div></section>';

var fazerConvite = '<img src="imgs/fazerConvite.jpg" alt="" height="500px"><section><p>Então o jovem decide convida-la para ir a casa dele para poder jogar video-game, e ela meio desconfiada pergunta para ele aonde que fica a casa dele, ele responde que ficava no bairro de Georgetown-Washington que não ficava muito longe do bar.<br>Ela confia nele vai em direção a casa dele, chegando la ela sem querer se depara com diversas coisas fora da realidade, como um robô futurista até mesmo para o tempo em que eles se encontravam, com funções jamais vistas antes.<br>O jovem fica sem jeito pois não era para ela descobrir sobre essas técnologias, era um segredo.</p><div class="botoes"><a onclick="carregarConteudo(falartdVerdade)" class="btn">Falar a verdade sobre seu estudo</a><a onclick="carregarConteudo(disfarcaOcorrido)" class="btn">Tentar disfarçar o ocorrido </a></div></section>';

var disfarcaOcorrido = '<img src="imgs/disfarcaOcorrido.jpg" alt="" height="500px"><section><p>Então o jovem tentar convencer ela sobre o que ele esta presenciando, na verdade foi um projeto programado pelo o amigo dele, mas mesmo assim ela fica desconfiada e fica quieta como se nada se estive acontecido, o jovem achava que tinha convencido ela, mas quando ela decidiu sair da casa dele.Ao sair da casa do jovem e mulher vai até delegacia e denuncia a casa dele, passando 4 horas uma viatura da polícia entra na casa do jovem e encontra diversas coisas fora da lei, a polícia era corrupta e decidiu vender toda aquela técnologia, mas havia um problema, ninguém poderia saber sobre as vendas, a bióloga que denunciou o jovem nunca mais ouviou falar dele...</p><div class="botoes"><a onclick="carregarConteudo(introducao)" class="btn">Jogar de novo</a></div></section>';

var deixardeLado = '<img src="imgs/deixardeLado.jpg" alt="" height="500px"><section><p>O jovem pensa bem e decide não chamar a garota para sua casa, e acaba se livrando de uma enrascada e tanto, atravessando a rua do boteco eles se despedem já que ambos moram e lugares totalmente diferentes.<br> A garota então fica curiosa para ver onde que ele morava, então começou a seguir  o mesmo caminho que ele trilhava, o jovem despercebido acaba  não  vendo que ela estava seguindo ele e acaba entrando em sua casa.<br> Então ela descobre onde ele morava, passando 4 horas depois ela decide voltar e chegando la o jovem esta se preparando para ir ao mercado e acaba esquecendo a porta destrancada.<br>  Ela aproveitou e entrou na casa, chegando la acabou se deparando com diversas coisas como armas biológicas fora da lei, neste exato momento o jovem  estava chegando do mercado, ela decide se esconder até ele se distrair, ela consegue se e acaba indo embora pela porta da frente. Saindo da casa ela avista um policial na rua, não muito longe e conta tudo que acabou de ver ao policial, ele então entra e para conferir e acaba encontrando diversas armas e estudos ilegais. O jovem ao voltar pra casa encontra a porta aberta e saca sua arma pensando que alguém tinha invadido, ele encontra os policiais de surpresa, e numa reação, os policiais balearam o jovem, ele tentou correr pra fora de sua casa, mas perdendo muito sangue enquanto corria, acaba morto no meio da rua.</p><div class="botoes"><a onclick="carregarConteudo(introducao)" class="btn">Jogar de novo</a></div></section>';

var falartdVerdade = '<img src="imgs/falartdVerdade.jpg" alt="" height="500px"><section><p>Então o jovem decide contar toda a verdade por trás de toda essas tecnologias, ela fica super impressionada já que nunca tinha visto algo assim antes. Mostrando um pouco mais suas invenções tecnológicas ela se depara com uma arma tecnológica com função a laser radiativo letal não permitida por lei. A moça percebe que ele esta escondendo armas ilegais em casa então fala para ele que precisava sair, que tinha um certo compromisso. O jovem abre a porta para ela, mas mal sabia o que estava por vir! Após sair ela vai direto em uma delegacia e denuncia o jovem,passando o endereço dele para os policias.<br>Chegando na casa dele acompanhado dos policias eles prendem o jovem com uma pena de prisão perpetua.<br>Ele fica no presidio ate aos 53 anos de idade.</p><div class="botoes"><a onclick="carregarConteudo(introducao)" class="btn">Jogar de novo</a></div></section>';

var irEmbora = '<img src="imgs/irEmbora.jpg" alt="" height="500px"><section><p>Quando saiu do boteco velho, após uma longa noite de bebedeira e contato com pessoas estranhas, ele resolveu dormir. Ao acordar, se sentiu envergonhado, achou que todos aqueles pensamentos não deveriam ter sido contados. O jovem, se olhou no espelho e disse a si mesmo, que iria parar de estudar sobre esses assuntos e, não iria mais duvidar de sua realidade, para o bem de sua saúde mental.</p><div class="botoes"><a onclick="carregarConteudo(viajarExcursao)" class="btn">Viajar em uma excursão</a><a onclick="carregarConteudo(casaEstudar)" class="btn">Ficar em casa estudando</a></div></section>';

var viajarExcursao = '<img src="imgs/viajarExcursao.jpg" alt="" height="500px"><section><p>O jovem programador, descobriu uma empresa que ficava perto de sua casa, era uma empresa de excursões. Ele resolveu fazer uma viagem para um museu que ficava em outra cidade, durante essa viagem, ele se sentou ao lado de uma garota metida a filósofa e intelectual. Essa viagem, durou 2 horas, tanto a ida quanto a volta, eles dois conversaram por 4 horas. A garota metida a intelectual, ao escutar o que o jovem programador dizia, ficou fascinado com toda aquela história. E isso, foi uma porta de entradas para o jovem programador ter sede de contar o que pensava. Eles viraram amigos, após estudarem essas ideias resolveram fazer o seguinte:</p><div class="botoes"><a onclick="carregarConteudo(derrubarAlgoritmo)" class="btn">Tentar derrubar o algoritmo</a><a onclick="carregarConteudo(receberRecompensas)" class="btn">Receber recompensas e ficar calado</a></div></section>';

var derrubarAlgoritmo = '<img src="imgs/derrubarAlgoritmo.jpg" alt="" height="500px"><section><p>Os dois, se aprofundaram bastante no assunto. A cada dia que passava, eles ficavam mais convictos de suas ideias. O jovem programador e sua amiga, a famosa "metida a intelectual", faziam de tudo para tornar os seus sonhos em uma realidade, conseguir fugir daquele mundo fantasioso e manipulador, voltando para o mundo real. O jovem programador, tinha em sua mente o modo de fugir daquele lugar, mas tinha medo do que podia acontecer. Ele tinha medo de ser eliminado para sempre pelos desenvolvedores daquele mundo. Ele muito estudioso e inteligente, pensou que se era possível criar um mundo e manipular pessoas, também era possível se tornar imortal dentro daquele mundo. E foi isso que eles fizeram, conseguiram se tornar imortais ali dentro. Os desenvolvedores do mundo real, criaram pessoas naquele mundo para tentar matar o jovem programador e sua amiga, mas ali dentro, eles alcançaram a imortalidade e conseguiram ser bem sucedidos nos seus planos. Eles conseguiram fugir daquele lugar e libertar as pessoas, mas tinham medo serem presos no mundo real. Os empresários de grandes empresas de inteligências artificiais, ficaram abismados com o que os jovens conseguiram fazer. O jovem programador, conseguiu o maior cargo dentro de uma empresa de tecnologia. A jovem metido intelectual, criou um canal no youtube para contar suas experiências dentro do mundo criado pelas máquinas, em poucos dias, conseguiu mais de 14 milhões de seguidores.</p><div class="botoes"><a onclick="carregarConteudo(introducao)" class="btn">Jogar de novo</a></div></section>';

var receberRecompensas = '<img src="imgs/receberRecompensas.jpg" alt="" height="500px"><section><p>No mundo real, sobrou apenas pessoas que não eram contra as inteligências artificiais, os que protestaram contra elas, foram controlados dentro de um sistema criado pelas máquinas, eles esqueceram totalmente os seus pensamentos anteriores do mundo real. Não se lembravam mais dos momentos alegres e nem das tristezas. Desenvolvedores de grandes empresas tecnológicas, perceberam que dentro desse sistema, tinham pessoas tentando fugir daquele mundo. Por esse motivo, eles ofereceram recompensas para hackers que tentavam derrubar o sistema. Eles ofereceram, carros, mansões, status, dinheiro e outros privilégios. A vontade de descobrir o mundo real e, sair daquela realidade que os cercavam, foi corrompida pela ganância.</p><div class="botoes"><a onclick="carregarConteudo(introducao)" class="btn">Jogar de novo</a></div></section>';



var elemento = document.getElementById("conteudo");

function carregarConteudo(conteudo) {
    elemento.innerHTML = conteudo;
}

carregarConteudo(introducao);


const body = document.querySelector("body");
const toggle = document.querySelector("#toggle");
const sunIcon = document.querySelector(".toggle .bxs-sun");
const moonIcon = document.querySelector(".toggle .bx-moon");

toggle.addEventListener("change", () => {

    body.classList.toggle("dark");
    sunIcon.className = sunIcon.className == "bx bxs-sun" ? "bx bx-sun" : "bx bxs-sun";
    moonIcon.className = moonIcon.className == "bx bxs-moon" ? "bx bx-moon" : "bx bxs-moon";

});